name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update build artifacts
